title: DynamiaTools
email: info@dynamiasoluciones.com
description: >- # this means to ignore newlines until "baseurl:"
  Fullstack Java 11+ framework for enterprise web applications
baseurl: ""
url: "https://dynamia.tools"
twitter_username: DynamiaTools
github_username:  dynamiatools
github_url: https://github.com/dynamiatools/framework
current_branch: main
logo: /assets/images/logo.png
icon: /assets/images/icon.png
stable_version: 4.0.5

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

sass:
    sass_dir: _sass

